In [5]:
# Built-in function/methods to create an array
import numpy as np

arr1 = np.zeros((3, 4), dtype = int)
print(arr1)
print(arr1.dtype)




[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [7]:
# Creating an array of ones
arr1 = np.ones((3, 4), dtype = int)
print(arr1)
print(arr1.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [11]:
# Creating an array of twos
arr1 = np.ones((3, 4), dtype = int)
print(arr1*2)
print(arr1.dtype)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
int64


In [12]:
# creating an empty array
np.empty((4,5))



array([[-1.28822975e-231, -1.28822975e-231,  9.38724727e-323,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 2.37663529e-312, -1.28822975e-231, -1.49457452e-154,
         1.48219694e-323,  0.00000000e+000]])

In [13]:
np.empty((3,4))

array([[1.e-323, 1.e-323, 1.e-323, 1.e-323],
       [1.e-323, 1.e-323, 1.e-323, 1.e-323],
       [1.e-323, 1.e-323, 1.e-323, 1.e-323]])

In [22]:
# Identity matrix

# 1 0 0 0 
# 0 1 0 0 
# 0 0 1 0
# 0 0 0 1

arr = np.eye(3)
# arr[::-1]
# arr.dtype = float
arr



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# linspace and arange

# arange(start, stop, step) - similar to range
# Difference between arange and range - arnage can create a sequence of float values

# arr = np.arange(2, 10, 1)
# print(arr)


# arr = np.arange(2, 10, 0.5)
# print(arr)


arr = np.linspace(2, 10, 90).reshape(15, 6)
print(arr)




[[ 2.          2.08988764  2.17977528  2.26966292  2.35955056  2.4494382 ]
 [ 2.53932584  2.62921348  2.71910112  2.80898876  2.8988764   2.98876404]
 [ 3.07865169  3.16853933  3.25842697  3.34831461  3.43820225  3.52808989]
 [ 3.61797753  3.70786517  3.79775281  3.88764045  3.97752809  4.06741573]
 [ 4.15730337  4.24719101  4.33707865  4.42696629  4.51685393  4.60674157]
 [ 4.69662921  4.78651685  4.87640449  4.96629213  5.05617978  5.14606742]
 [ 5.23595506  5.3258427   5.41573034  5.50561798  5.59550562  5.68539326]
 [ 5.7752809   5.86516854  5.95505618  6.04494382  6.13483146  6.2247191 ]
 [ 6.31460674  6.40449438  6.49438202  6.58426966  6.6741573   6.76404494]
 [ 6.85393258  6.94382022  7.03370787  7.12359551  7.21348315  7.30337079]
 [ 7.39325843  7.48314607  7.57303371  7.66292135  7.75280899  7.84269663]
 [ 7.93258427  8.02247191  8.11235955  8.20224719  8.29213483  8.38202247]
 [ 8.47191011  8.56179775  8.65168539  8.74157303  8.83146067  8.92134831]
 [ 9.01123596  9.1011236 

In [32]:
# 8/89

In [38]:
# Changing the shape of an array
# reshape(), shape

# reshape creates a new object
# shape attribute makes the changes to existing object

# arr = np.linspace(2, 10, 90)

# arr1 = arr.reshape(15, 6)
# print(arr1)
# print()
# print(arr)

# arr.shape = (15,6)

# print(arr)






[[ 2.          2.08988764  2.17977528  2.26966292  2.35955056  2.4494382 ]
 [ 2.53932584  2.62921348  2.71910112  2.80898876  2.8988764   2.98876404]
 [ 3.07865169  3.16853933  3.25842697  3.34831461  3.43820225  3.52808989]
 [ 3.61797753  3.70786517  3.79775281  3.88764045  3.97752809  4.06741573]
 [ 4.15730337  4.24719101  4.33707865  4.42696629  4.51685393  4.60674157]
 [ 4.69662921  4.78651685  4.87640449  4.96629213  5.05617978  5.14606742]
 [ 5.23595506  5.3258427   5.41573034  5.50561798  5.59550562  5.68539326]
 [ 5.7752809   5.86516854  5.95505618  6.04494382  6.13483146  6.2247191 ]
 [ 6.31460674  6.40449438  6.49438202  6.58426966  6.6741573   6.76404494]
 [ 6.85393258  6.94382022  7.03370787  7.12359551  7.21348315  7.30337079]
 [ 7.39325843  7.48314607  7.57303371  7.66292135  7.75280899  7.84269663]
 [ 7.93258427  8.02247191  8.11235955  8.20224719  8.29213483  8.38202247]
 [ 8.47191011  8.56179775  8.65168539  8.74157303  8.83146067  8.92134831]
 [ 9.01123596  9.1011236 

In [43]:
arr = np.linspace(2, 10, 90)

# arr.reshape(9, -1)

# arr.reshape(10, -1)

arr.shape = 10, -10

arr

array([[ 2.        ,  2.08988764,  2.17977528,  2.26966292,  2.35955056,
         2.4494382 ,  2.53932584,  2.62921348,  2.71910112],
       [ 2.80898876,  2.8988764 ,  2.98876404,  3.07865169,  3.16853933,
         3.25842697,  3.34831461,  3.43820225,  3.52808989],
       [ 3.61797753,  3.70786517,  3.79775281,  3.88764045,  3.97752809,
         4.06741573,  4.15730337,  4.24719101,  4.33707865],
       [ 4.42696629,  4.51685393,  4.60674157,  4.69662921,  4.78651685,
         4.87640449,  4.96629213,  5.05617978,  5.14606742],
       [ 5.23595506,  5.3258427 ,  5.41573034,  5.50561798,  5.59550562,
         5.68539326,  5.7752809 ,  5.86516854,  5.95505618],
       [ 6.04494382,  6.13483146,  6.2247191 ,  6.31460674,  6.40449438,
         6.49438202,  6.58426966,  6.6741573 ,  6.76404494],
       [ 6.85393258,  6.94382022,  7.03370787,  7.12359551,  7.21348315,
         7.30337079,  7.39325843,  7.48314607,  7.57303371],
       [ 7.66292135,  7.75280899,  7.84269663,  7.93258427,  8

In [45]:
# Transpose - converts rows to columns and columns to rows

arr.T


array([[ 2.        ,  2.80898876,  3.61797753,  4.42696629,  5.23595506,
         6.04494382,  6.85393258,  7.66292135,  8.47191011,  9.28089888],
       [ 2.08988764,  2.8988764 ,  3.70786517,  4.51685393,  5.3258427 ,
         6.13483146,  6.94382022,  7.75280899,  8.56179775,  9.37078652],
       [ 2.17977528,  2.98876404,  3.79775281,  4.60674157,  5.41573034,
         6.2247191 ,  7.03370787,  7.84269663,  8.65168539,  9.46067416],
       [ 2.26966292,  3.07865169,  3.88764045,  4.69662921,  5.50561798,
         6.31460674,  7.12359551,  7.93258427,  8.74157303,  9.5505618 ],
       [ 2.35955056,  3.16853933,  3.97752809,  4.78651685,  5.59550562,
         6.40449438,  7.21348315,  8.02247191,  8.83146067,  9.64044944],
       [ 2.4494382 ,  3.25842697,  4.06741573,  4.87640449,  5.68539326,
         6.49438202,  7.30337079,  8.11235955,  8.92134831,  9.73033708],
       [ 2.53932584,  3.34831461,  4.15730337,  4.96629213,  5.7752809 ,
         6.58426966,  7.39325843,  8.20224719

In [46]:
arr

array([[ 2.        ,  2.08988764,  2.17977528,  2.26966292,  2.35955056,
         2.4494382 ,  2.53932584,  2.62921348,  2.71910112],
       [ 2.80898876,  2.8988764 ,  2.98876404,  3.07865169,  3.16853933,
         3.25842697,  3.34831461,  3.43820225,  3.52808989],
       [ 3.61797753,  3.70786517,  3.79775281,  3.88764045,  3.97752809,
         4.06741573,  4.15730337,  4.24719101,  4.33707865],
       [ 4.42696629,  4.51685393,  4.60674157,  4.69662921,  4.78651685,
         4.87640449,  4.96629213,  5.05617978,  5.14606742],
       [ 5.23595506,  5.3258427 ,  5.41573034,  5.50561798,  5.59550562,
         5.68539326,  5.7752809 ,  5.86516854,  5.95505618],
       [ 6.04494382,  6.13483146,  6.2247191 ,  6.31460674,  6.40449438,
         6.49438202,  6.58426966,  6.6741573 ,  6.76404494],
       [ 6.85393258,  6.94382022,  7.03370787,  7.12359551,  7.21348315,
         7.30337079,  7.39325843,  7.48314607,  7.57303371],
       [ 7.66292135,  7.75280899,  7.84269663,  7.93258427,  8

In [47]:
# To convert an arry of higher tdimension to one dimension
arr.ravel()

array([ 2.        ,  2.08988764,  2.17977528,  2.26966292,  2.35955056,
        2.4494382 ,  2.53932584,  2.62921348,  2.71910112,  2.80898876,
        2.8988764 ,  2.98876404,  3.07865169,  3.16853933,  3.25842697,
        3.34831461,  3.43820225,  3.52808989,  3.61797753,  3.70786517,
        3.79775281,  3.88764045,  3.97752809,  4.06741573,  4.15730337,
        4.24719101,  4.33707865,  4.42696629,  4.51685393,  4.60674157,
        4.69662921,  4.78651685,  4.87640449,  4.96629213,  5.05617978,
        5.14606742,  5.23595506,  5.3258427 ,  5.41573034,  5.50561798,
        5.59550562,  5.68539326,  5.7752809 ,  5.86516854,  5.95505618,
        6.04494382,  6.13483146,  6.2247191 ,  6.31460674,  6.40449438,
        6.49438202,  6.58426966,  6.6741573 ,  6.76404494,  6.85393258,
        6.94382022,  7.03370787,  7.12359551,  7.21348315,  7.30337079,
        7.39325843,  7.48314607,  7.57303371,  7.66292135,  7.75280899,
        7.84269663,  7.93258427,  8.02247191,  8.11235955,  8.20

In [48]:
# Ordersing = 
#     1. C like ordering - 'C'
#     2. Forton Like ordering - 'F'

arr1 = np.arange(1, 11)
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
arr1.reshape((2, 5), order ='C')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
arr1.reshape((2, 5), order ='F')

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

# Operations on an array
        - Arithmetic Operation
        - Comparions
        - Equality 







In [54]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([11,22,33,44,55])

print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)    # Scalar product





[ 21  42  63  84 105]
[-1 -2 -3 -4 -5]
[ 110  440  990 1760 2750]


In [56]:
# Product
#     1. Scalar
#     2. Vector - np.dot(arr1, arr2)
        # 1. No of col in first array and no of row in 2nd array should be same
        # 2. shape of resultant aray is (no of rows of 1st Array X no of cols of 2nd array)


# print(arr1*4)
# print(arr1*arr2)




[ 40  80 120 160 200]
[ 110  440  990 1760 2750]


In [67]:
arr1 = np.array([[1, 2, 3, 4, 5]])


arr2 = np.array([[6],
                 [7],
                 [8],
                 [9],
                 [10]])

print(arr1*arr2)



[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]


In [ ]:
[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

[[6, 6, 6, 6, 6],
 [7, 7, 7, 7, 7],
 [8, 8, 8, 8, 8],
 [9, 9, 9, 9, 9],
 [10,10,10,10,10]]

In [ ]:
np.dot()

In [64]:
arr1 = np.arange(25, 55).reshape(5, 6)
arr1

arr2 = np.arange(25, 61).reshape(6, 6)
arr2

print(arr1*arr2)

ValueError: operands could not be broadcast together with shapes (5,6) (6,6) 

In [68]:
np.dot(arr1, arr2)

array([[130]])

In [72]:
arr3 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8 ]])

arr4 = np.array([[9,8, 10],
                 [7,6, 11],
                 [5,4, 12],
                 [3,2, 13]])

print(np.dot(arr3, arr4))

[[ 50  40 120]
 [146 120 304]]


In [74]:
# Comparison operation
# Returns a boolean matrix

arr1 = np.arange(25, 55).reshape(5, 6)
np.random.shuffle(arr1)


In [75]:
arr1

array([[25, 26, 27, 28, 29, 30],
       [43, 44, 45, 46, 47, 48],
       [37, 38, 39, 40, 41, 42],
       [31, 32, 33, 34, 35, 36],
       [49, 50, 51, 52, 53, 54]])

In [77]:
arr1[arr1>40]

array([43, 44, 45, 46, 47, 48, 41, 42, 49, 50, 51, 52, 53, 54])

In [78]:
arr1 = np.random.randint(1, 100, (5, 6))
arr1

array([[ 9, 27, 31, 74, 47, 20],
       [28, 32, 25, 70, 34, 98],
       [89, 10, 19, 30, 73,  9],
       [27, 69, 75, 82,  8, 67],
       [61, 60, 61, 30, 27, 43]])

In [79]:
arr2 = np.random.randint(1, 100, (5, 6))
arr2

array([[10, 88, 45,  4, 85, 60],
       [61, 58, 87, 72, 50, 11],
       [94, 84, 45, 10, 57, 42],
       [80, 79, 31, 35, 65, 61],
       [59, 41, 16, 36, 81, 58]])

In [81]:
arr1 > arr2

array([[False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False,  True,  True, False],
       [False, False,  True,  True, False,  True],
       [ True,  True,  True, False, False, False]])

In [90]:
# Compound assignment operation

# arr1 += arr2
# arr1


19+89+183+107+120

518

In [84]:
# Unary Operations

np.sum(arr1)



2940

In [85]:
np.max(arr1)

183

In [86]:
np.min(arr1)

19

In [91]:
arr1

array([[ 19, 115,  76,  78, 132,  80],
       [ 89,  90, 112, 142,  84, 109],
       [183,  94,  64,  40, 130,  51],
       [107, 148, 106, 117,  73, 128],
       [120, 101,  77,  66, 108, 101]])

In [88]:
# Sum of all the elements along rows and columns

# Along rows
np.sum(arr1, axis = 0)



array([518, 548, 435, 443, 527, 469])

In [89]:
# Along columns
np.sum(arr1, axis = 1)

array([500, 626, 562, 679, 573])

In [93]:
np.max(arr1, axis = 0)


array([183, 148, 112, 142, 132, 128])

In [94]:
np.max(arr1, axis = 1)

array([132, 142, 183, 148, 120])

In [98]:
# INdexing and slicing on numpy array

arr1 = np.array([1,2,3,4,5,6,7,8,9])
# print(arr1[0])
# print(arr1[-1])

print(arr1[2:6])
print(arr1)





[3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [104]:
arr1 = np.random.randint(1, 100, (6, 6))
arr1


# Indexing on. 2D array
# arr_name[row_ind, col_ind]
# arr_name[row_Slicing, col_slicing]

array([[56, 38, 73, 75, 29, 82],
       [31, 11, 49, 74, 35, 91],
       [28, 50, 35, 54, 35, 24],
       [76, 60, 56, 48,  7, 77],
       [18, 41, 40, 44, 28,  2],
       [70, 38, 68, 72, 71, 90]])

In [103]:
# Accessing one row
print(arr1[0])
print(arr1[-1])

[51 41  6 64 78 90]
[86 70 90 23  4 93]


In [105]:
print(arr1[0][0])

56


In [107]:
# Accessing a column

print(arr1[::, 0])

[56 31 28 76 18 70]


In [109]:
# Accessing a column
print(arr1[::, -1])

[82 91 24 77  2 90]


In [110]:
print(arr1[2, 2])

35


In [111]:
arr1

array([[56, 38, 73, 75, 29, 82],
       [31, 11, 49, 74, 35, 91],
       [28, 50, 35, 54, 35, 24],
       [76, 60, 56, 48,  7, 77],
       [18, 41, 40, 44, 28,  2],
       [70, 38, 68, 72, 71, 90]])

In [112]:
print(arr1[1::2])

[[31 11 49 74 35 91]
 [76 60 56 48  7 77]
 [70 38 68 72 71 90]]


In [113]:
print(arr1[::,1::2])

[[38 75 82]
 [11 74 91]
 [50 54 24]
 [60 48 77]
 [41 44  2]
 [38 72 90]]


In [114]:
print(arr1[3::, 3::])

[[48  7 77]
 [44 28  2]
 [72 71 90]]


In [115]:
print(arr1[1:4:2, 1:4:2])

[[11 74]
 [60 48]]


In [117]:
arr1

array([[56, 38, 73, 75, 29, 82],
       [31, 11, 49, 74, 35, 91],
       [28, 50, 35, 54, 35, 24],
       [76, 60, 56, 48,  7, 77],
       [18, 41, 40, 44, 28,  2],
       [70, 38, 68, 72, 71, 90]])

In [120]:
row_ind = [[1,2],[3,2]]
col_ind = [[2,1],[2,3]]

In [121]:
arr1[row_ind, col_ind]

array([[49, 50],
       [56, 54]])

In [126]:
# 3D array
arr1 = np.random.randint(1, 100, (4, 5, 6))
arr1[1:3][1][1::2, 1::2]

array([[84, 52, 65],
       [89, 38, 97]])

In [128]:
arr1 = np.random.randint(1, 100, (6, 6, 6))
arr1

array([[[71, 39, 73, 42,  5, 89],
        [60, 58, 52, 42,  1, 65],
        [37, 15,  5, 14, 11, 97],
        [ 3, 83,  3, 46, 68, 97],
        [88, 27, 47, 52, 46, 92],
        [96, 13, 36, 37, 46, 85]],

       [[66, 90, 12, 96, 26, 32],
        [76, 43,  5, 11, 33, 90],
        [97, 97,  3, 93, 38, 11],
        [77, 61, 98,  7, 74, 16],
        [78, 45, 81, 28, 98,  9],
        [67, 32, 96, 88, 22, 35]],

       [[81, 61, 43, 16, 90, 93],
        [64, 51, 31, 52, 94, 46],
        [63, 36, 38, 80, 47, 74],
        [17, 93, 39,  8, 22, 59],
        [88, 91, 42, 88, 36, 74],
        [18, 21, 15, 68, 64, 82]],

       [[42, 70, 81, 25, 54, 16],
        [92, 67,  7, 72, 93, 21],
        [49, 22,  3, 18, 66, 50],
        [76, 66, 73, 65, 50, 65],
        [46, 73, 34, 59, 58, 56],
        [42, 10, 85, 29, 82, 57]],

       [[49, 83, 26, 71, 89, 68],
        [58,  3, 16, 21,  1, 96],
        [37, 89, 98, 47, 28, 19],
        [56,  9, 50, 23, 28, 34],
        [ 9, 62, 39, 22, 79, 29],
      

In [131]:
arr1[::2][1][::3, ::3]

array([[81, 16],
       [17,  8]])

In [132]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [133]:
k = np.array([[0,1],[1,2]])
k

array([[0, 1],
       [1, 2]])

In [134]:
v = np.array([[2,1],[3,3]])
v

array([[2, 1],
       [3, 3]])

In [136]:
fruit[k, v] = 'Watermelon'

In [137]:
fruit

array([['Banana', 'Mango', 'Watermelon', 'Avacado'],
       ['Papaya', 'Watermelon', 'Plum', 'Watermelon'],
       ['Apricot', 'Apple', 'Blue berry', 'Watermelon']], dtype='<U11')

In [138]:
arr1 = np.random.randint(1, 100, (6, 6))
arr1

array([[17, 41,  4, 26, 81, 84],
       [78, 28, 98, 16, 98, 84],
       [94, 82, 73, 93, 62, 81],
       [58, 76, 57, 60,  2, 19],
       [13,  7, 39, 12, 98,  6],
       [96, 49, 51, 92,  8, 99]])

In [139]:
arr1[arr1>50]

array([81, 84, 78, 98, 98, 84, 94, 82, 73, 93, 62, 81, 58, 76, 57, 60, 98,
       96, 51, 92, 99])

In [140]:
# How many element which are greater than 50

np.sum(arr1>50)



21

In [141]:
np.any(arr1>50)

True

In [142]:
np.all(arr1>50)

False